### ISSUE TITLE
More proper name for `LineSensor`

### ISSUE THREAD

**Issue by tiwanari** [PileProject/drivecommand#17]
I think `LineSensor` ([here](https://github.com/PileProject/drivecommand/blob/develop/src/main/java/com/pileproject/drivecommand/machine/device/input/LineSensor.java)) is too specific name for the sensor and propose to replace the name with `LightSensor`.

**Comment by mandaiy** [comment]
To me it makes sense.
How about you @amiq11?

**Comment by tiwanari** [comment]
ping @amiq11 

If you agree with the opinion, I'll fix it :)

**Comment by tiwanari** [comment]
This was solved by #23 :)
