### ISSUE TITLE
Proposal of reducing the size of this repository

### ISSUE THREAD

**Issue by tiwanari** [PileProject/drivecommand#19]
## Problem statement
Our repository is so big that it takes us a long time to clone. I briefly checked the cause (see [this article](http://qiita.com/kaneshin/items/0d19fc1cd86f931dc855) for more information) and it may be the history of `design` materials.

## Proposal
I'd like to propose to delete the history of `design` materials. They seem not not be updated and I think JavaDocs can do the role. 

I will use the following command to delete them.

```shell
git filter-branch --index-filter "git rm -r --cached --ignore-unmatch ${target}" -- --all
```

## Discussion
If you say it is okay, I will do that.

**Comment by tiwanari** [comment]
i also noticed that the history of some old `*.jar` files (e.g., android.jar) takes up substantial volume.

**Comment by mandaiy** [comment]
👍

**Comment by tiwanari** [comment]
I made a simple script.

```sh
#!/bin/sh
TARGETS=(
  "libs"
  "lib"
  "design"
  "doc"
  "coverage-report"
)
target=$(printf " %s" "${TARGETS[@]}")
target=${target:1}

git filter-branch -f --index-filter "git rm -f -r --cached --ignore-unmatch ${target}" -- --all
```
and before&after is
```
[ tatsuya@tatsuyas-MBP ] drivecommand# du -sh .git/objects
 20M	.git/objects
```
to
```
[ tatsuya@tatsuyas-MBP ] drivecommand-clean-tmp-check# du -sh .git/objects
672K	.git/objects
```

**Comment by tiwanari** [comment]
It looks good, doesn't it? 🎉 

I will force push if you give me an approval! :)

**Comment by tiwanari** [comment]
I checked it can be built (`./gradlew build javadoc`). If you want to check, it is [here](https://github.com/tiwanari/drivecommand-clean-tmp-check/tree/develop).

**Comment by tiwanari** [comment]
Then, let me push :)

**Comment by tiwanari** [comment]
I pushed them :sunglasses:
